name: Deploy to GCP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/791907021272/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: terraform-deployer@hr-management-2025.iam.gserviceaccount.com
          token_format: access_token

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan - Artifact Registry
        run: terraform plan -target=module.artifact_registry

      - name: Terraform Apply - Artifact Registry
        run: terraform apply -auto-approve -target=module.artifact_registry

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/hr-management-2025/calculator-repo-ga/calculator:latest

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve